### ISSUE TITLE
Unable to install on VS 2017 15.6.2

### ISSUE THREAD

**Issue by Chaosmeister** [tyoma/micro-profiler#35]
![image](https://user-images.githubusercontent.com/13346344/37525845-303dc112-292e-11e8-8067-c83457b5c0af.png)

![image](https://user-images.githubusercontent.com/13346344/37525881-45571404-292e-11e8-97af-17122935439f.png)

the log says:

```
16.03.2018 15:26:14 - Die Erweiterung mit der ID A42F6081-855F-41CB-8C89-9488AA847290 wird nicht für Microsoft Visual Studio Professional 2017 installiert.
16.03.2018 15:26:16 - Die Erweiterung kann für die folgenden Produkte aufgrund fehlender erforderlicher Komponenten nicht installiert werden:
16.03.2018 15:26:16 - 	Microsoft Visual Studio Professional 2017
16.03.2018 15:26:16 - 		-------------------------------------------------------
16.03.2018 15:26:16 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
16.03.2018 15:26:16 - 		Name         : Visual Studio core editor
16.03.2018 15:26:16 - 		Version      : [11.0,15.0]
16.03.2018 15:26:16 - 		Error        : Die angegebene erforderliche Version entspricht nicht der installierten Version.
16.03.2018 15:26:16 - 
16.03.2018 15:26:16 - System.InvalidOperationException: No modifications could be applied.
   at VSIXInstaller.MultipleChangePage..ctor(ExtensionData data)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass11_1.<OnLoaded>b__2()
```

roughly translated:
```
Extension ID A42F6081-855F-41CB-8C89-9488AA847290 will not be installed
The extension cannot be installed because of missing components:
[...]
Error: The requested version does not match the installed version
```

**Comment by tyoma** [comment]
Thanks!
Probably, this is due to ..., 15.0] - they may have increased minor verion... I'll update VS 2017 and check.

**Comment by tyoma** [comment]
I was able to reproduce and found another issue with context menu specific to micro-profiler. Both are now fixed as of v1.2.597. Please, re-get the extension from the MarketPlace or from Visual Studio built-in 'Extensions & Updates'.
Once you confirm that error has gone, please, close the issue.
Thank you!

**Comment by Chaosmeister** [comment]
Installation from the gallery / Extensions and Updates worked.
I had a little bit trouble with the previous installation, but was able to solve it by manually removing `micro-profiler_x64.lib` and `micro-profiler.initializer.cpp` from all projects, where they were left.

I can't run it with the debugger though: 
![image](https://user-images.githubusercontent.com/13346344/37599193-676bca64-2b84-11e8-920d-89447885ede4.png)

rough translation: 
``` 
Systemerror

Cannot continue code execution because of missing micro-profiler_x64.dll.
This issue may be resolved by reinstalling.
```

Starting without debugging shows the microprofiler but does not profile.

I'm not sure how to clean my installation, yet.

**Comment by Chaosmeister** [comment]
Ah `enable profiling` was off for the build. 🤦‍♂️ 

It works If I start without debugging.

**Comment by tyoma** [comment]
Did you try relogon/restart? Can you check (after the restart) if the MICROPROFILERDIR environment variable points to a proper location, where micro-profiler_x64.dll can be found?

**Comment by tyoma** [comment]
Thank you!
